output:
  strategy: firebase

firebase:
  database_url: "https://docs-lab4-default-rtdb.firebaseio.com"
  credentials_path: "config/docs-lab4-firebase-adminsdk-fbsvc-c12d5a1ba8.json"
  root_node: "air_quality_data3"
  write_mode: "set"
  batch_size: 100
  
dataset:
  url: "https://data.cityofnewyork.us/resource/dsyc-npkh.json"
  local_path: "data/air_quality.csv"
  limit: 500

kafka:
  bootstrap_servers: "localhost:9092"
  topic: "air_quality_data"
  client_id: "air_quality_producer"
  message_format: "json"

redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null
  key_prefix: "air_quality"
  ttl: null
  storage_type: "hash"
